version: "3.4"

services:
  chatbot-server:
    image: chatbot-server
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3111:3000
    networks:
      - database
    volumes:
      - ~/upload/chatbot-server:/upload
networks:
  database:
    external:
      name: database
